### ISSUE TITLE
When screen layout changes windows are not sized properly.

### ISSUE THREAD

**Issue by hramrach** [xmonad/xmonad#190] opened 2019-03-13 17:22 UTC
### Problem Description

Specifically I switched from layout with two monitors with different height by turning off the taller monitor. The window on the remaining shorter monitor grows gap below it that is about proportional to the difference in height between the two monitors. I cannot remove the gap. Floating and un-floating the window does not fix the layout.

**Comment by liskin** [comment] 2021-07-25 14:38
Is this still a problem? Can you perhaps include some photos, screenshots, videos? And your config, too.

**Comment by hramrach** [comment] 2021-07-26 12:08
Is there any reason this should not be a problem anymore?

I don't have a multi-screen setup at hand to test at the moment.

The problem probably comes from the fact that the desktop is logically rectangular even if it contains holes, and the hole is not correctly removed when screens configuration changes.

<pre>
+-------------+--------+
|  hole       |        |
+-------------+ Window2|
|             |        |
| Window1     |        |
|             |        |
+-------------+--------+
  (hole offscreen -  windows correspond to screens)

           V

+-------------+
|  hole       |        
+-------------+ 
| Window1     |        
|             |
+-------------+
  (hole onscreen -  remaining screen has window and hole)
</pre>

**Comment by liskin** [comment] 2021-07-26 12:22
> Is there any reason this should not be a problem anymore?

Other than you figuring it out, and possibly bugs being fixed, no.

The thing is, I've been using xmonad with dynamically changing monitor layouts for 12 years, and never seen this. I also know how monitors/screens are handled internally, and there is no notion of holes, xmonad just takes whatever xinerama screens there are and displays a workspace on each. So as long as your xrandr configuration is okay, this can't (shouldn't) happen.

There is some notion of holes in X.H.ManageDocks, which could lead to a similar issue, provided some buggy software creates a misplaced hole, like this one: https://github.com/jaor/xmobar/issues/530 (which is now fixed in xmobar).

There's also https://github.com/xmonad/xmonad/issues/47 which seems remarkably similar to your issue.

Anyway, if we want to fix this, we need to see it first. So if you can reproduce it somewhere, I'd really love to see a video of it, and then your configuration (ideally shrinked to only contain the bits necessary to still trigger the bug).

**Comment by hramrach** [comment] 2021-07-27 17:48
FWIW I am using lxpanel, gkrellm, hsetroot and  xcompmgr with xmonad, mostly in monocle layout.

The system with multiple screens is not easily accessible so it will take a while to test if it's reproducible.

**Comment by geekosaur** [comment] 2021-07-27 17:52
For what it's worth, I have seen something like this and it's actually the fault of xrandr mislocating the remaining screen for some reason. I avoid connecting/disconnecting monitors while running because of it. I don't know why xrandr does this but (when I can get the window to show at all) it shows in arandr and other graphical display management utilities.

**Comment by hramrach** [comment] 2021-07-27 18:00
Right, and nVidia drivers are not really great at xrandr so this may be the root cause. Any way to dump the xrandr state?

**Comment by geekosaur** [comment] 2021-07-27 18:01
Run the xrandr command; by default it lists the current state.

**Comment by liskin** [comment] 2021-07-27 19:44
Hm, with Xorg server 1.20.11 and xrandr 1.5.0 I can't make it create a gap like the one pictured in https://github.com/xmonad/xmonad/issues/190#issuecomment-886644849. Whenever I `--off` the output on the right, xrandr moves the left screen to 0x0. I tried with both modesetting driver and nvidia 460.73.01. :-/

**Comment by liskin** [comment] 2021-07-27 20:04
Even if I [patch this functionality out of xrandr](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=512919), I can't reproduce the issue.

```
Screen 0: minimum 320 x 200, current 1920 x 1527, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+447 (normal left inverted right x axis y axis) 309mm x 173mm
```

Everything still works normally, including xmobars.

**Comment by slotThe** [comment] 2022-04-05 06:55
I will close this due to lack of reproducibility

**Closed as completed by slotThe** 2022-04-05 06:55 UTC
Labels: needs: reproducibility
