### ISSUE TITLE
XMonad freezes if I choose another window while XMonad prompt is waiting for an input.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad#116] opened 2017-05-25 12:22 UTC
### Problem Description

I noticed this problem while I was using `XMonad.Prompt.ConfirmPrompt`.

While `XMonad.Prompt.ConfirmPrompt` is waiting for an input, if I try to give focus to another window, XMonad completely freezes.

I have to kill xmonad in virtual terminal.

Since `focusFollowsMouse = True` in my XMonad environment, moving a mouse cursor while a confirm prompt is waiting can freeze XMonad.

I surmise this is a problem of lack of concurrency in `X`.

A workaround is to avoid `X` and use `xfork` and `MonadIO m => m`. This is possible by replacing `XMonad.Prompt.ConfirmPrompt` with my own implementation of dmenu prompt.

**Comment by crocket** [comment] 2017-06-12 02:52
What about `forkX`? It's named after `forkIO` from `Control.Concurrent`.

**Comment by geekosaur** [comment] 2017-06-12 03:14
It's not so much concurrency as that when you are in Prompt, you are not in the run loop and can't switch focus. That said, I don't think it should freeze, it should simply not process the mouse movement as a focus switch (because that's a main event loop response and it is not the main event loop that is running, it's Prompt's event loop) --- unless Prompt itself is trying to be too clever, in which case it does need to be rewritten differently.

`forkX` is not an ideal solution if what you select is intended to modify xmonad's state; it would need to send the action back to the main thread via an X11 `sendMessage`. It's fine if all you are doing is spawning something, though. But if it needs to modify xmonad state then either it needs to operate by setting a flag for a `handleEventHook` to intercept and process events before xmonad itself does, or run in a thread and send the action back to the main thread as I described.

**Comment by crocket** [comment] 2017-06-12 04:17
That sounds complicated. Is there a minimal example of an ideal solution?

**Comment by de-vri-es** [comment] 2019-09-29 20:56
> It's not so much concurrency as that when you are in Prompt, you are not in the run loop and can't switch focus. That said, I don't think it should freeze, it should simply not process the mouse movement as a focus switch (because that's a main event loop response and it is not the main event loop that is running, it's Prompt's event loop) --- unless Prompt itself is trying to be too clever, in which case it does need to be rewritten differently.

I was looking at the implementation, and I can't find any code related to handling mouse input. Which is fine for the prompt of course, but I also couldn't really see if the code is *ignoring* mouse input.

Is it possible that mouse events are still processed outside of the prompt event loop somehow?

Keep in mind I'm no Haskell star, nor that familiar with the way X works. So I may have overlooked something.

/edit: I guess this is filtering events:
https://github.com/xmonad/xmonad-contrib/blob/60101b9a7071575c27ec905ccd02c01887d49200/XMonad/Prompt.hs#L619-L623

So that leaves the question: why does clicking another window (or moving over one with `focusFollowsMouse`) still focus that window and freeze everything?

/edit2: I'm actually not 100% sure the other window is focussed. All I know is that everything stops responding to input.

/edit3:
I ran `xprop -spy -root _NET_ACTIVE_WINDOW`, and it doesn't change when the freeze happens. So xmonad isn't updating `_NET_ACTIVE_WINDOW` at that point. Could it be that X itself is doing something when you click a window?

**Comment by geekosaur** [comment] 2019-09-30 15:44
Mouse events aren't handled at all, per the `XMaskEvent` call (`maskEvent` in Haskell). But only the keyboard is grabbed, so the event may be handled by some other listening client, leading to an attempt to change the focused window which will be ignored by the XP event loop, leading to an effective lock-up because the keyboard hasn't been ungrabbed so Prompt is still eating all keystrokes. Do remember that X11 is concurrent, and other clients are still running and still getting events unless a grab has been done on some class of events (here, keyboard events only).

This would behave more as you expect if either (a) events were consumed via the main event loop and the `handleEventHook` as described above, or (b) `runXP` responded to unexpected events by dropping its grab and deleting the window. But it looks to me like it treats it as an unknown key and keeps running.

**Comment by geekosaur** [comment] 2019-09-30 15:46
Possibly `runXP` should also capture mouse events (also grabbing the mouse to avoid them going to an unexpected client) and immediately dropping its grab and closing its window.

**Comment by crocket** [comment] 2020-08-18 08:26
Any update on this issue?

**Comment by bitdizzy** [comment] 2020-08-25 15:17
I started taking a look at this because it's affecting me as well. After adding some traces to the prompt event loop I was surprised to find that after the click event that causes the lock-up the event loop was not finding any more key events to process, but it was still getting expose events as can be triggered by switching to a vty and back. I'm not quite sure what to investigate next as the Haskell code seems to be operating as expected-- it's just not getting any keyboard events to respond to. I might try to use xscope to sniff between the server and XMonad but setting that up is a bit involved.

**Comment by bitdizzy** [comment] 2020-08-25 23:49
I reproduced the issue with xmonad running in Xephyr. From the xscope output, it looks like the Xserver just stops responding entirely at the point where the freeze occurs:

```
03 5e eb 8c 00 63 00 00 00 0a 00 60 00 00 00 00 00 14 03 44 01 06 03 42 01 00 
00 01 00 
					 ..............EVENT: ButtonPress
					              detail: 1 (^A)
					     sequence number: 0337
					                time: TIM 008ceb5e
					                root: WIN 00000063
					               event: WIN 0060000a
					               child: None
					              root-x: 788
					              root-y: 324
					             event-x: 774
					             event-y: 322
					               state: 0
					         same-screen: True
Have 0 need 32
42.46: 					  32 bytes <-- X11 Server 3
					               Event (fd 9): 05 01 37 
03 5e eb 8c 00 63 00 00 00 0a 00 60 00 00 00 00 00 14 03 44 01 06 03 42 01 00 
01 01 00 
					 ..............EVENT: ButtonRelease
					              detail: 1 (^A)
					     sequence number: 0337
					                time: TIM 008ceb5e
					                root: WIN 00000063
					               event: WIN 0060000a
					               child: None
					              root-x: 788
					              root-y: 324
					             event-x: 774
					             event-y: 322
					               state: Button1
					         same-screen: True
Have 0 need 32
43.43: 					  32 bytes <-- X11 Server 1
					               Event (fd 5): 07 04 d1 
09 30 ef 8c 00 63 00 00 00 08 00 40 00 0c 00 40 00 c8 03 53 01 08 00 53 01 00 
00 00 02 
					 ..............EVENT: EnterNotify
					              detail: NonlinearVirtual
					     sequence number: 09d1
					                time: TIM 008cef30
					                root: WIN 00000063
					               event: WIN 00400008
					               child: WIN 0040000c
					              root-x: 968
					              root-y: 339
					             event-x: 8
					             event-y: 339
					               state: 0
					                mode: Normal
					  same-screen, focus: same-screen
Have 0 need 32
45.25: 					  64 bytes <-- X11 Server 1
					               Event (fd 5): 07 02 d1 
09 44 f6 8c 00 63 00 00 00 08 00 40 00 00 00 00 00 c2 05 a2 01 02 02 a2 01 00 
01 01 02 
					 ..............EVENT: EnterNotify
					              detail: Inferior
					     sequence number: 09d1
					                time: TIM 008cf644
					                root: WIN 00000063
					               event: WIN 00400008
					               child: None
					              root-x: 1474
					              root-y: 418
					             event-x: 514
					             event-y: 418
					               state: Button1
					                mode: Grab
					  same-screen, focus: same-screen
					               Event (fd 5): 04 01 d1 
09 44 f6 8c 00 63 00 00 00 08 00 40 00 0a 00 40 00 c2 05 a2 01 02 02 a2 01 00 
00 01 00 
					 ..............EVENT: ButtonPress
					              detail: 1 (^A)
					     sequence number: 09d1
					                time: TIM 008cf644
					                root: WIN 00000063
					               event: WIN 00400008
					               child: WIN 0040000a
					              root-x: 1474
					              root-y: 418
					             event-x: 514
					             event-y: 418
					               state: 0
					         same-screen: True
```

Here, the first button press and release are on the window that was focused when the prompt was open. The last event is the last event from the server, a press on a different window.

I don't know how to get Xephyr to be gabby about what it's doing, so the next step is probably to attach gdb and see what's going on in there. :pensive:

**Comment by bitdizzy** [comment] 2020-08-29 23:24
So, killing the client that owns the window that would have received the click unfreezes everything. I don't know very much about Xserver or what obligations Xmonad has to respond to events like this click to make sure things keep moving along. Watching the server do its thing, device input events _are_ being processed in full, but they're not going to any client _until_ the freeze stops.

I also tried having XPrompt grab button events as well, but that didn't help! Maybe I did it wrong. I'll have to try again.

**Comment by fvhockney** [comment] 2021-01-09 19:19
This was biting me today too. I managed a work around in my config

```haskell
foo :: (Window -> X()) -> X()
foo f = withWindowSet $ \ws -> do
    let current' = W.integrate' . W.stack . W.workspace . W.current $ ws
    let visible' = concatMap(W.integrate' . W.stack . W.workspace) (W.visible $ ws) in
        forM_ (current' ++ visible') f

("M-s", (foo $ setButtonGrab False) >>
    sshPrompt def >>
    (foo $ setButtonGrab True))
```

This prevents clicks from freezing x and prompt retains focus/continues to grab input. One downside that I've noticed is that mouse modifier (Mod4 + Drag floats for me) seem to be passed through but don't take effect until after the prompt finishes.

I'm essentially modifying the `withAll` action to grab the workspaces visible on my other screen. I _think_ that this should work for an arbitrary number of additional screens, including 0.

My haskell is virtually non-existant, but I'm sure that if we could figure out how to get a list of all visible windows and `setButtonGrab`, that this would work as at least a temporary solution.

**Closed as completed** 2021-01-27 16:43 UTC
