### ISSUE TITLE
RGB Terminal w3m-img display 

### ISSUE THREAD

**Issue by zyklotomic** [xmonad/xmonad#68] opened 2017-01-11 08:15 UTC
I remember Geekosaur told me on #xmonad freenode that there was an upcoming fix for RGB terminals. I use ranger and have turned on image preview which uses the w3m-img image server.  Termite shows the images properly on other WM's. On XMonad, ranger with urxvt properly shows the images, but not with termite. 

I remember Geekosaur told me that this is a known bug and was in the process of getting patched?

**Comment by geekosaur** [comment] 2017-01-11 15:36
On Wed, Jan 11, 2017 at 3:15 AM, zyklotomic <notifications@github.com>
wrote:

> I remember Geekosaur told me that this is a known bug and was in the
> process of getting patched?


We have no control over someone patching w3m for RGBA support. The  RGBA
patch for xmonad is not specific to terminals, and does not affect whether
other programs support RGBA; it only affects the visibility of xmonad's
window borders.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by pjones** [comment] 2017-01-17 01:42
@zyklotomic As geekosaur mentioned, the patch only has to do with window borders.

That said, I'd be interested in seeing some screenshots so I can better understand the issue you are describing.

**Comment by zyklotomic** [comment] 2017-01-22 14:47
![2017-01-22-102728_2560x1600_scrot](https://cloud.githubusercontent.com/assets/22725085/22183251/6dfa813a-e0f4-11e6-8567-5ed9156f6342.png)

This is with compton on. Notice how the borders of the urxvt terminal are opaque and has image preview working and the termite terminal with borders transparent doesn't have the image preview working. xfce4-term also has transparent borders when compton is turned on. xfce4-term also doesn't work with image preview. 

I suspect that it has to do with why compton makes the terminal borders transparent.

**Comment by geekosaur** [comment] 2017-01-22 14:54
If you mean image preview not working --- please try it with a different window manager *with compositing*.

Because the problem is that w3m is ancient and *does not support compositing at all*. Nothing to do with the window manager; if the window you are rendering into uses an RGBA visual, w3m-img will not work. The only way the border is related is that we were *also* mishandling borders in RGBA windows (and X.L.WindowNavigation still is). Fixing how xmonad draws its borders will not somehow rewrite a 12-years-unmaintained image renderer to handle RGBA visuals; if you want w3m-img to work in Termite, you will have to get the source to w3m-img and modify it to support RGBA visuals instead of crashing with a BadMatch X11 error.

**Comment by geekosaur** [comment] 2017-01-22 15:01
(specifically re `w3m-img`: it allocates an RGB pixmap, gets the window `XID`, and tries to `XCopyArea`. Since the depth of the RGB pixmap is 24 and the depth of the RGBA window is 32, `XCopyArea` fails with a `BadMatch` X11 error, as documented in the [manpage](https://linux.die.net/man/3/xcopyarea).)

**Comment by pjones** [comment] 2017-02-07 00:33
@zyklotomic If you are only referring to the terminal borders being transparent then we did fix that bug.  Have you tried using XMonad from git?

I'm closing this issue since this is already fixed if we are talking about the borders.  If we're not talking about the borders then the issue isn't related to XMonad.

**Closed as completed by pjones** 2017-02-07 00:33 UTC

**Comment by zyklotomic** [comment] 2017-02-10 02:11
I was talking about both. I was thinking if the two issues were related.
Yes, the transparent borders have been fixed for me

Thanks!
