### ISSUE TITLE
Xmonad compatibility with RandR >= 1.4 and dual-GPUs in multihead

### ISSUE THREAD

**Issue by haudren** [xmonad/xmonad#60] opened 2016-12-02 08:55 UTC
I was using xmonad in a very satisfying fashion until the fateful day when I upgraded the nvidia drivers on my Ubuntu laptop, powered by an Optimus enabled GPU.

My typical workflow was to:
- Set the window arrangement with `xrandr`,  typically along the lines of `xrandr --output eDP --auto --output DP-0 --right-of eDP`. Note that the integrated graphics is connected to the Intel chip while the external ports are connected to the discrete NVIDIA card.
- Start xmonad with the appropriate number of screens (workspaces = withScreens 2 $ map show [1..9]).
It worked very well.

With the latest update (nvidia-331 => nvidia-367, I also checked a few in between with the same results), xrandr succeeds without problems in turning on both displays but xmonad only uses one screen, in my case the external display:
- xmobar only appears on that screen
- It is impossible to move a window to/from a screen to the other with <ctrl+w/e>
- Impossible of course to open a window in this display

I wonder if there is any way to fix this?

Accessing Xlib from Haskell or Python, I can see the following:
- screen_count is `1`
- screen resolution is 3840x1080, so both screens merged
- xrrGetScreenResources does return all modes for both screens, so there is probably a way to identify them there
- nvidia-settings only report one screen (the external one, connected to the nvidia card)

Finally, let me say that Xmonad is not alone in this... I tried:
- Unity presents a garbled display, stretched across screens and basically unusable
- Gnome with Xmonad fails to start
- Xfce works just fine
- Xmonad in Xfce does not behave better

Thanks for the great software :)

**Comment by liskin** [comment] 2016-12-02 09:37
I'm not sure what's causing this particular problem of yours (it looks like something with Xinerama), but it seems your X server is running primarily on the nvidia card and I don't think you want that on a laptop, due to power management (keeping the nvidia card powered on consumes quite a few watts). I've been using a similar setup for years and currently it looks like this:

 - bumblebee and bbswitch from debian package to power nvidia down when not in use
 - bumblebee configured to use nvidia drivers (367.57-2 at the moment) and not nouveau
 - intel-virtual-output that takes pixels from intel's framebuffer and puts them onto nvidia's (also, intel-virtual-output talks to bumblebee and asks it to power nvidia up and so on so you don't need to do that manually)

So, if your laptop isn't sitting connected to AC all day long (in which case you shouldn't have bought a laptop in the first place), you may want to try a similar setup. That is, unless you need that rendering power of nvidia. In my case, I use either intel-virtual-output for triplehead or primusrun for games, but never need both at the same time. If you need nvidia outputs and nvidia opengl at the same time, just disregard my whole reply. :-)

**Comment by haudren** [comment] 2016-12-02 09:42
Well the laptop is sitting connected to AC all day, because it was a company-bought laptop and I can't really affect policy... Then, I work with two displays (one connected to the discrete graphics), and I do need the Nvidia power to render our 3D simulations, so I'm afraid your solution is not applicable :sob: 

I thought that bumblebee was abandoned in favor of prime, but I must be mistaken.

**Comment by liskin** [comment] 2016-12-02 09:49
I think we'll need to wait a few more years until prime is really usable as a replacement.
[nvidia readme](http://us.download.nvidia.com/XFree86/Linux-x86_64/375.20/README/randr14.html) says: "The NVIDIA driver currently only supports the Source Output capability. It does not support render offload and cannot be used as an output sink." which basically means that if power management is a concern, you're out of luck.

**Comment by haudren** [comment] 2016-12-02 10:00
Power management is not really a concern, but multihead display is :( I guess I'll content myself with one display for the time being, maybe it's time to upgrade to 4K :smile: 

I also installed awesome, and it seems to me that it behaves the same as xmonad, so I wonder what xfce is doing right (or wrong) compared to everyone else...

**Comment by haudren** [comment] 2016-12-05 09:13
So I actually checked, using the python bindings for X that I am more used to:
```python
from Xlib import X, display, Xutil
from Xlib.ext import xinerama, randr

display = display.Display()

print("X: {} screens".format(display.screen_count()))
for index in range(display.screen_count()):
  print("X_screen_{}: {}x{}".format(index, display.screen(index).width_in_pixels,
                                    display.screen(index).height_in_pixels))

screen = display.screen()
window = screen.root.create_window(0, 0, 3840, 1080, 1, screen.root_depth)

xin_count = xinerama.get_screen_count(window).screen_count
print("Xinerama: {} screens").format(xin_count)
for index in range(xin_count):
  scr_size = xinerama.get_screen_size(window, index)
  print("Xinerama_screen_{}: {}x{}".format(index, scr_size.width, scr_size.height))
```

Prints out:
```
X: 1 screens
X_screen_0: 3840x1080
Xinerama: 1 screens
Xinerama_screen_0: 1920x1080
```
So `xinerama` only gets one screen... I am currently working on getting the same kind of information from `randr` which should be more correct (in my case).

**Comment by liskin** [comment] 2016-12-05 09:32
You need Xinerama to return more than 1 screen. That's what xmonad (and every other multihead-aware X application out there) uses to get the display layout.

**Comment by haudren** [comment] 2016-12-05 09:36
I understand this pretty well (except XFCE apparently): however, I have no idea on how to "force" xinerama to return two displays. If you have any idea, I'll take it. As I saw that RandR is supposed to [supersede xinerama](https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt#n2244), and seeing that it returns the correct arrangement from command line, I figured I'd give it a go.

**Comment by liskin** [comment] 2016-12-05 09:52
Some info about Xinerama is here: http://us.download.nvidia.com/XFree86/Linux-x86_64/375.20/README/xconfigoptions.html#nvidiaXineramaInfo and here: http://us.download.nvidia.com/XFree86/Linux-x86_64/375.20/README/configtwinview.html (Will window managers be able to appropriately place windows (e.g., avoiding placing windows across both display devices, or in inaccessible regions of the virtual desktop)?)

**Comment by haudren** [comment] 2016-12-05 09:52
Ok the following python code:
```python
scr_info = randr.get_screen_info(window)
scr_size = scr_info.sizes[scr_info.size_id]
print("Xrandr_total_size: {}x{}").format(scr_size.width_in_pixels, scr_size.height_in_pixels)

scr_resources = randr.get_screen_resources(window)

for crtc_id in scr_resources.crtcs:
  crtc = randr.get_crtc_info(display, crtc_id, scr_resources.config_timestamp)
  if(crtc.outputs):
    print("Xrandr_screen_{}: {}x{}+{}x{}".format(crtc_id, crtc.width, crtc.height, crtc.x, crtc.y))
```
Correctly returns:
```
Xrandr_total_size: 3840x1080
Xrandr_screen_709: 1920x1080+1920x0
Xrandr_screen_63: 1920x1080+0x0
```

Which means that if it was possible to switch screens detection from Xinerama to RandR I might be able to solve my problem.

**Comment by haudren** [comment] 2016-12-05 10:17
Ok thanks for the help:
- If i disable "nvidiaXineramaInfo", xmonad treats my multi-monitor setup as a single big monitor, which is not such a big problem with two equal-sized monitors.
- If I manually set "nvidiaXineramaInfoOverride" with the appropriate string, it works just fine.

I guess this means that nvidia is not properly reporting xinerama info in my case, while it is correctly reported by xrandr. I guess I'll stick to manual configuration for the time being, unless someone deems worthy to include a patch in case xinerama reports incorrect info.

**Comment by liskin** [comment] 2016-12-05 10:18
You might also want to report the issue to nvidia. :-)

**Comment by haudren** [comment] 2016-12-05 11:05
Reported there :) Should I close the issue ? There may be some interest in at least diagnosing the issue (i.e. when xinerama does not report the same total size as the Xscreen) and warning the user.

**Comment by geekosaur** [comment] 2016-12-05 16:56
On Mon, Dec 5, 2016 at 9:36 AM, Hervé Audren <notifications@github.com>
wrote:

> As I saw that RandR is supposed to supersede xinerama
> <https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt#n2244>
> ,
>

This is only half true. Xinerama had two components: the high level one
which is superseded, and the low level protocol for carving multiple
monitor viewports out of a single common root window which is still there,
still required by XRandR, still in -lxinerama, and probably never going
away or getting rebranded/renamed.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by geekosaur** [comment] 2016-12-05 16:57
On Mon, Dec 5, 2016 at 10:17 AM, Hervé Audren <notifications@github.com>
wrote:

> I guess this means that nvidia is not properly reporting xinerama info in
> my case


Yes, this is a longstanding NVidia bug.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by pjones** [comment] 2016-12-09 16:30
I'm closing this issue since the problem isn't being caused in xmonad and there is nothing we can do to resolve it.  If that changes please feel free to reopen the issue or create a new one.  Good luck.

**Closed as completed by pjones** 2016-12-09 16:30 UTC

**Comment by haudren** [comment] 2016-12-13 04:34
I just wanted to comment, that the NVidia support told me that is "normal" that the NVidia driver does not report the screens attached to the Intel card... I guess I'll stick with my hack, at least for the time being.

Thank you all for your time.

**Comment by jbeard4** [comment] 2017-05-05 05:32
@haudren I am affected by this issue as well. I was unable to find where you sourced the "nvidiaXineramaInfoOverride" workaround, and I was wondering if you could please elaborate on how you got this working? Thank you for your help.

**Comment by jbeard4** [comment] 2017-05-05 05:51
Hi, 

Please disregard my previous question. I was able to work around this by setting the following options in xorg.conf, under Section "Screen" (for triple-head display):

```
    Option "nvidiaXineramaInfo" "True"
    Option "nvidiaXineramaInfoOverride" "1920x1080+1920+0, 1920x1080+0+0, 1920x1080+3840+0"
```

Thank you for pointing me in the right direction.

**Comment by kalj** [comment] 2018-02-26 19:39
I have similar problem, but it seems there is some minor difference since Xinerama seems to actually manage to detect the second monitor. If I run the first script here, I get:

    X: 1 screens
    X_screen_0: 3840x1080
    Xinerama: 2 screens
    Xinerama_screen_0: 3840x1080
    Xinerama_screen_1: 3840x1080

Still, I only get one big screen spanning both monitors and xmonad only recognizes the first monitor as usable space. 

The following test mentioned in the Xmonad FAQ also seems successful:

    $  ghc -e "Graphics.X11.openDisplay [] >>= Graphics.X11.Xinerama.getScreenInfo"
    [Rectangle {rect_x = 0, rect_y = 0, rect_width = 1920, rect_height = 1080},Rectangle {rect_x = 1920, rect_y = 0, rect_width = 1920, rect_height = 1080}]

Can someone help me understand what my issue might be?

**Comment by geekosaur** [comment] 2018-02-27 03:23
Is this xmonad 0.13, and had you used the same version in a single-monitor configuration before? Because this is what happens if you have a stale `xmonad.state` file from a single-monitor configuration: it contains layout state information, which has embedded within it the then-current screen configuration. A workaround for an active session is to force relayout, which is mod-shift-space with the default key bindings. Then change session startup to remove any existing `xmonad.state` file, or install xmonad from git instead of 0.13 release.

**Comment by kalj** [comment] 2018-02-28 19:04
@geekosaur Wow, that was interesting. I do use xmonad 0.13, and if I made sure to remove that file before logging in, it actually works as it should. I now see that this is issue #90. However, I was not able to see any effect from mod-shift-space though. For me, that only resets the layout on the current workspace. Are all of these things fully functional in the git version? Maybe it is worth installing that then, but I'd rather not go through that process if I can avoid it.
